### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by navaneethperfit** [picorana/amazon-scraper#11]
Traceback (most recent call last):
  File "/usr/local/bin/amazon-scraper", line 11, in <module>
    load_entry_point('amazon-scraper==0.0.1', 'console_scripts', 'amazon-scraper')()
  File "/usr/local/lib/python2.7/site-packages/amazon_scraper-0.0.1-py2.7.egg/amazon_scraper/app.py", line 463, in main
    scraper.scrape() 
  File "/usr/local/lib/python2.7/site-packages/amazon_scraper-0.0.1-py2.7.egg/amazon_scraper/app.py", line 73, in scrape
    main_reviews_url, review_pages_number = self.retrieve_page(asin)
  File "/usr/local/lib/python2.7/site-packages/amazon_scraper-0.0.1-py2.7.egg/amazon_scraper/app.py", line 324, in retrieve_page
    "div", { "id" : "reviews-medley-footer" }
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by Sicks3c** [comment]
I have the same issue

**Comment by JasonCrowe** [comment]
I don't think this package is maintained any longer. It hasn't worked (as is) for quite a long time.
